---
# Task file for roles/provision_spyro/tasks/main.yml

- name: Install solr-ssh tpkg
  shell: echo {{ solr_ssh_password }} | /usr/bin/tpkg -i solr-ssh -n
  sudo: yes
  tags: 
    - configuration
    - tpkg
- name: Install the required spyro utils tpkg
  shell: /usr/bin/tpkg -i {{ item }} -n
  sudo: yes
  with_items:
    - spyro_api_mogwai
    - srco_spyro_ulimit
    - srco_spyro_newrelic
  tags:
    - configuration
    - tpkg
- name: Install mysql-proxy-config-searchcat tpkg
  shell: echo {{ searchcat_config_password }} | /usr/bin/tpkg -i mysql-proxy-config-searchcat -n
  sudo: yes
  notify: start mysql proxy
  tags:
    - configuration
    - tpkg
- name: "Copy production wc1 .spyrorc env file if this is a wc1 production host"
  copy: src=prod/wc1_spyrorc dest=/home/solr/.spyrorc owner=solr group=roleusers mode=0660
  when: "'{{ inventory_hostname }}' in {{ groups['production'] }} and '{{ inventory_hostname }}' in {{ groups['wc1'] }}"
- name: "Copy production ev1 .spyrorc env file if this is a ev1 production host"
  copy: src=prod/ev1_spyrorc dest=/home/solr/.spyrorc owner=solr group=roleusers mode=0660
  when: "'{{ inventory_hostname }}' in {{ groups['production'] }} and '{{ inventory_hostname }}' in {{ groups['ev1'] }}"
- name: "Copy stage wc1 .spyrorc env file if this is a stage wc1 host"
  copy: src=stage/wc1_spyrorc dest=/home/solr/.spyrorc owner=solr group=roleusers mode=0660
  when: "'{{ inventory_hostname }}' in {{ groups['stage'] }} and '{{ inventory_hostname }}' in {{ groups['wc1'] }}"
- name: Install spyro tpkg
  shell: /usr/bin/tpkg -i {{ spyro_tpkg_version }} -n
  sudo: yes
  tags:
    - configuration
    - tpkg